# -*- coding: utf-8 -*-
"""Copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bv2ktytfzy5mvNMDXnwETq9xhv6zH7Xp

# Welcome to Colab!
"""

print ("Hello, Data Science!")

nama = "Rega Kurnia Saputra"
angkatan = 2024

print(f"halo, nama saya {nama} angakatan {angkatan}")

tools = ["Python", "Google Colab", "Jupyter Notebook", "GitHub"]
for i, tool in enumerate(tools, 1):
  print (f"{i}.{tool}")

def perkenalan(nama, prodi, angkatan):
  return f"{nama} | {prodi} | {angkatan}"
print(perkenalan("Rega Kurnia Saputra", "Informatika", "2024"))